-- Synthetic machine-day observations; no seeded predictions or invented asset counts.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA RAW;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE TABLE RAW.MACHINES AS
WITH equipment AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS MACHINE_INDEX
  FROM TABLE(GENERATOR(ROWCOUNT => 20))
)
SELECT 'MAC-' || LPAD(MACHINE_INDEX::VARCHAR, 4, '0') AS ID,
       'Synthetic machine ' || (MACHINE_INDEX + 1) AS NAME,
       CASE MOD(MACHINE_INDEX, 5)
         WHEN 0 THEN 'Ho Chi Minh City' WHEN 1 THEN 'Hanoi'
         WHEN 2 THEN 'Binh Duong' WHEN 3 THEN 'Dong Nai' ELSE 'Can Tho' END AS REGION,
       CASE MOD(MACHINE_INDEX, 4)
         WHEN 0 THEN 'Pick and Place' WHEN 1 THEN 'Reflow Oven'
         WHEN 2 THEN 'AOI Station' ELSE 'Conveyor' END AS CATEGORY,
       MACHINE_INDEX,
       'Active' AS STATUS
FROM equipment;

CREATE TABLE RAW.SENSOR_READINGS AS
WITH days AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS DAY_INDEX
  FROM TABLE(GENERATOR(ROWCOUNT => 90))
), observations AS (
  SELECT machine.ID AS ENTITY_ID, machine.MACHINE_INDEX, days.DAY_INDEX,
         DATEADD('day', days.DAY_INDEX - 89, CURRENT_DATE()) AS EVENT_DATE,
         24.0 AS PLANNED_HOURS,
         IFF(MOD(days.DAY_INDEX + machine.MACHINE_INDEX * 3, 17) = 0, 1, 0) AS FAILURE_COUNT,
         IFF(MOD(days.DAY_INDEX + machine.MACHINE_INDEX * 3, 17) = 0,
             1.0 + MOD(machine.MACHINE_INDEX, 4) * 0.5, 0.0) AS DOWNTIME_HOURS,
         IFF(MOD(days.DAY_INDEX, 7) = 0, 1, 0) AS PM_DUE,
         IFF(MOD(days.DAY_INDEX, 7) = 0 AND MOD(days.DAY_INDEX + machine.MACHINE_INDEX, 5) <> 0, 1, 0) AS PM_COMPLETED,
         1000 + MOD(machine.MACHINE_INDEX, 5) * 100 AS TOTAL_UNITS
  FROM RAW.MACHINES machine CROSS JOIN days
)
SELECT ENTITY_ID || '-' || TO_CHAR(EVENT_DATE, 'YYYYMMDD') AS EVENT_ID,
       ENTITY_ID, EVENT_DATE, PLANNED_HOURS, DOWNTIME_HOURS,
       PLANNED_HOURS - DOWNTIME_HOURS AS OPERATING_HOURS,
       FAILURE_COUNT,
       CASE WHEN FAILURE_COUNT = 0 THEN 'None'
            WHEN MOD(MACHINE_INDEX, 3) = 0 THEN 'Bearing wear'
            WHEN MOD(MACHINE_INDEX, 3) = 1 THEN 'Thermal excursion'
            ELSE 'Alignment' END AS ROOT_CAUSE,
       PM_DUE, PM_COMPLETED, TOTAL_UNITS,
       FLOOR(TOTAL_UNITS * (0.93 + 0.04 * PM_COMPLETED - 0.02 * FAILURE_COUNT)) AS GOOD_UNITS,
       100.0 * (PLANNED_HOURS - DOWNTIME_HOURS) / PLANNED_HOURS AS KPI_EQUIPMENT_UPTIME,
       2.0 + MOD(DAY_INDEX + MACHINE_INDEX, 17) * 0.12 AS VIBRATION_MM_S,
       55.0 + MOD(DAY_INDEX + MACHINE_INDEX, 17) * 0.9 AS TEMPERATURE_C,
       CURRENT_TIMESTAMP() AS LOADED_AT
FROM observations;

CREATE TABLE RAW.SPARE_PARTS AS
SELECT ID AS ENTITY_ID, 'Drive assembly' AS PART_TYPE,
       2 AS REQUIRED_QTY, IFF(MOD(MACHINE_INDEX, 4) = 0, 1, 2) AS ON_HAND_QTY,
       IFF(MOD(MACHINE_INDEX, 4) = 0, 1, 0) AS ON_ORDER_QTY,
       CURRENT_DATE() AS SNAPSHOT_DATE
FROM RAW.MACHINES;
