-- On-demand snapshots. No automatic five-minute freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT machine.ID AS ENTITY_ID, machine.NAME AS ENTITY_NAME,
       machine.REGION, machine.CATEGORY, machine.STATUS,
       COUNT(*) AS EVENT_COUNT, SUM(observation.FAILURE_COUNT) AS ALERT_COUNT,
       SUM(observation.OPERATING_HOURS) AS OPERATING_HOURS,
       SUM(observation.PLANNED_HOURS) AS PLANNED_HOURS,
       SUM(observation.DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(observation.PM_DUE) AS PM_DUE, SUM(observation.PM_COMPLETED) AS PM_COMPLETED,
       SUM(observation.GOOD_UNITS) AS GOOD_UNITS, SUM(observation.TOTAL_UNITS) AS TOTAL_UNITS,
       100.0 * SUM(observation.OPERATING_HOURS) / NULLIF(SUM(observation.PLANNED_HOURS), 0) AS AVG_EQUIPMENT_UPTIME,
       SUM(observation.OPERATING_HOURS) / NULLIF(SUM(observation.FAILURE_COUNT), 0) AS AVG_MTBF,
       100.0 * SUM(observation.PM_COMPLETED) / NULLIF(SUM(observation.PM_DUE), 0) AS PM_COMPLIANCE_PCT,
       100.0 * SUM(observation.GOOD_UNITS) / NULLIF(SUM(observation.TOTAL_UNITS), 0) AS YIELD_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.SENSOR_READINGS observation
JOIN RAW.MACHINES machine ON machine.ID = observation.ENTITY_ID
GROUP BY machine.ID, machine.NAME, machine.REGION, machine.CATEGORY, machine.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(OPERATING_HOURS) AS OPERATING_HOURS, SUM(PLANNED_HOURS) AS PLANNED_HOURS,
       SUM(FAILURE_COUNT) AS FAILURE_COUNT,
       100.0 * SUM(OPERATING_HOURS) / NULLIF(SUM(PLANNED_HOURS), 0) AS AVG_EQUIPMENT_UPTIME,
       SUM(OPERATING_HOURS) / NULLIF(SUM(FAILURE_COUNT), 0) AS AVG_MTBF
FROM RAW.SENSOR_READINGS
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.DOWNTIME_CAUSES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ROOT_CAUSE, SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(FAILURE_COUNT) AS FAILURE_COUNT
FROM RAW.SENSOR_READINGS
WHERE FAILURE_COUNT > 0
GROUP BY ROOT_CAUSE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(OPERATING_HOURS) AS OPERATING_HOURS, SUM(PLANNED_HOURS) AS PLANNED_HOURS,
         SUM(FAILURE_COUNT) AS FAILURES, MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.SENSOR_READINGS
), fleet AS (SELECT COUNT(*) AS EQUIPMENT_COUNT FROM RAW.MACHINES),
spares AS (
  SELECT SUM(ON_ORDER_QTY) AS ON_ORDER_QTY,
         100.0 * SUM(LEAST(ON_HAND_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT
  FROM RAW.SPARE_PARTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Equipment Uptime' AS TITLE,
         100.0 * OPERATING_HOURS / NULLIF(PLANNED_HOURS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Unplanned Stops', FAILURES, '' FROM observations
  UNION ALL SELECT 3, 'MTBF (Avg)', OPERATING_HOURS / NULLIF(FAILURES, 0), ' hrs' FROM observations
  UNION ALL SELECT 4, 'Equipment Managed', EQUIPMENT_COUNT, '' FROM fleet
  UNION ALL SELECT 6, 'Parts on Order', ON_ORDER_QTY, '' FROM spares
  UNION ALL SELECT 7, 'Spare Coverage', COVERAGE_PCT, '%' FROM spares
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1)) || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.DOWNTIME_CAUSES SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
