-- Failure-risk scoring and downtime forecast over the synthetic snapshot.
-- Replaces the former "RUL" placeholder: the data has no run-to-failure history,
-- so we predict P(failure in next 7 days) instead and report holdout metrics.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.FAILURE_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, m.CATEGORY, m.AGE_YEARS,
       r.VIBRATION_MM_S, r.TEMPERATURE_C,
       AVG(r.VIBRATION_MM_S) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS VIBRATION_7D,
       SUM(r.FAILURE_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS FAILURES_30D,
       IFF(SUM(r.FAILURE_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'FAIL', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.SENSOR_READINGS r JOIN RAW.MACHINES m ON m.ID = r.ENTITY_ID
WHERE r.ROOT_CAUSE <> 'Power disturbance' OR r.FAILURE_COUNT = 0;

-- Time-based split: train on older labelled days, hold out the most recent labelled 14 days.
CREATE VIEW ML.FAILURE_TRAIN AS
SELECT CATEGORY, AGE_YEARS, VIBRATION_MM_S, TEMPERATURE_C, VIBRATION_7D, FAILURES_30D, LABEL
FROM ML.FAILURE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.FAILURE_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, AGE_YEARS, VIBRATION_MM_S, TEMPERATURE_C, VIBRATION_7D, FAILURES_30D, LABEL
FROM ML.FAILURE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.FAILURE_RISK_MODEL(
  INPUT_DATA => TABLE(ML.FAILURE_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.FAILURE_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.FAILURE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'VIBRATION_MM_S', VIBRATION_MM_S,
           'TEMPERATURE_C', TEMPERATURE_C, 'VIBRATION_7D', VIBRATION_7D, 'FAILURES_30D', FAILURES_30D)):probability:FAIL::FLOAT AS P
  FROM ML.FAILURE_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'FAIL', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'FAIL', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'FAIL', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'FAIL', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per machine (label unknown, so excluded from features).
CREATE TABLE ML.FAILURE_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.FAILURE_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.FAILURE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'VIBRATION_MM_S', VIBRATION_MM_S,
           'TEMPERATURE_C', TEMPERATURE_C, 'VIBRATION_7D', VIBRATION_7D, 'FAILURES_30D', FAILURES_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:FAIL::FLOAT, 4) AS FAILURE_PROB_7D,
       CASE WHEN P:probability:FAIL::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:FAIL::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Fleet downtime forecast (14 days) from the daily series.
CREATE VIEW ML.DAILY_DOWNTIME AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS
FROM RAW.SENSOR_READINGS GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.DOWNTIME_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_DOWNTIME),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'DOWNTIME_HOURS'
);

CREATE TABLE ML.DOWNTIME_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS DOWNTIME_HOURS,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.DOWNTIME_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
