-- ============================================================================
-- 99_RESET.SQL — Reset Predictive Maintenance to clean demo state
-- ============================================================================
USE DATABASE ELECTRONICS_MAINTENANCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PERFORMANCE_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.FORECAST_INPUT REFRESH;
ALTER DYNAMIC TABLE CURATED.OPERATIONAL_RISK REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ELECTRONICS_MAINTENANCE.RAW.OPERATIONS → 100000
-- SELECT COUNT(*) FROM ELECTRONICS_MAINTENANCE.RAW.METRICS → 500000
-- SELECT COUNT(*) FROM ELECTRONICS_MAINTENANCE.ML.ELECTRONICS_MAINTENANCE_FORECAST_RESULTS → >0

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST RESUME;
